#ifndef C4D_SYMBOLS_H__
#define C4D_SYMBOLS_H__

enum {
	// string table definitions
	STUDIOLIGHTSCOMMANDTITLE = 10000,

	ID_STUDIOLIGHTS_OBJECT_FILLLIGHT,
	ID_STUDIOLIGHTS_OBJECT_KEYLIGHT,
	ID_STUDIOLIGHTS_OBJECT_BACKLIGHT,

	

	_DUMMY_ELEMENT_
};

#endif // C4D_SYMBOLS_H__