
#ifndef OSTUDIOLIGHTS_H__
#define OSTUDIOLIGHTS_H__

enum {
	STUDIOLIGHTS_TEST = 1000,

	// General Properties
	ID_STUDIOLIGHTS_GENERAL_TARGET_LINKBOX,

	// Light Properties
	ID_STUDIOLIGHTS_LIGHT_TARGET_CHECKBOX,

	ID_STUDIOLIGHTS_LIGHT_FILLLIGHT_GROUP,
	ID_STUDIOLIGHTS_LIGHT_FILLLIGHT_TOGGLE,
	ID_STUDIOLIGHTS_LIGHT_FILLLIGHT_BRIGHTNESS,
	ID_STUDIOLIGHTS_LIGHT_FILLLIGHT_COLOR,

	ID_STUDIOLIGHTS_LIGHT_KEYLIGHT_GROUP,
	ID_STUDIOLIGHTS_LIGHT_KEYLIGHT_TOGGLE,
	ID_STUDIOLIGHTS_LIGHT_KEYLIGHT_BRIGHTNESS,
	ID_STUDIOLIGHTS_LIGHT_KEYLIGHT_COLOR,

	ID_STUDIOLIGHTS_LIGHT_BACKLIGHT_GROUP,
	ID_STUDIOLIGHTS_LIGHT_BACKLIGHT_TOGGLE,
	ID_STUDIOLIGHTS_LIGHT_BACKLIGHT_BRIGHTNESS,
	ID_STUDIOLIGHTS_LIGHT_BACKLIGHT_COLOR,

	

	// Camera Properties
	ID_STUDIOLIGHTS_CAMERA_TARGET_CHECKBOX,

	// Stage Properties
	ID_STUDIOLIGHTS_STAGE_LENGTH,

	ID_STUDIOLIGHTS_GENERAL,
	ID_STUDIOLIGHTS_LIGHTS,
	ID_STUDIOLIGHTS_CAMERA,
	ID_STUDIOLIGHTS_STAGE
};

#endif // OSTUDIOLIGHTS_H__
